server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: BankAPI
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_DB:bank}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA:public}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml
    default-schema: ${DATABASE_SCHEMA:public}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: API
        url: /v3/api-docs

security:
  jwt:
    secret: ${JWT_SECRET:X3jRNEuPGg54l6SX3jRNEuPGg54l6SX3jRNEuPGg54l6SX3jRNEuPGg54l6S}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
